# Generated by Django 4.0.5 on 2022-06-13 09:49

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='position',
            field=mapbox_location_field.models.LocationField(default=(0, 0), map_attrs={}),
            preserve_default=False,
        ),
    ]
